version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: poker.mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pokerdb

#volumes:
#  poker_mongodb_data: