version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: poker.mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
