version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: poker.mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pokerdb

  nginx:
    image: nginx
    container_name: poker.nginx
    ports:
      - 8080:80
    links:
      - api
    volumes:
      - ./var/logs/nginx:/var/log/nginx
      - ./docker/nginx/sites:/etc/nginx/conf.d

  api:
    image: docker.pkg.github.com/abashkatov/poker-api/poker-api:latest
    container_name: poker.api
    restart: always
    links:
      - mongo
    environment:
      - SERVER_PORT=80
      - SPRING_DATA_MONGODB_HOST=poker.mongo

#volumes:
#  poker_mongodb_data: