name: Build and deploy

on:
  release:
    types:
      - created
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Gradle
        run: gradle build
      - name: Upload
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "./build/libs/*"
          target: ${{ secrets.DEPLOY_PATH }}/${{ github.event.release.tag_name }}
      - name: Add link and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            ln -s ${{ secrets.DEPLOY_PATH }}/${{ github.event.release.tag_name }} ${{ secrets.DEPLOY_PATH }}/current
            systemctl restart poker-api.service